(part "AS312"
    (packageRef "AS312")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "REL") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VSS") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Senba Optoelectronic")
    (property "Manufacturer_Part_Number" "AS312")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Through Hole Sensor and Detector Interfaces RoHS")
    (property "Datasheet_Link" "https://www.lcsc.com/product-detail/C90465.html")
    (property "symbolName1" "AS312")
)
