(part "TP4056"
    (packageRef "SOIC127P600X175-9N")
    (interface
        (port "1" (symbPinId 1) (portName "TEMP1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PROG2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VCC4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "BAT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "%STDBY%") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%CHRG%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "CE") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "NanJing Top Power")
    (property "Manufacturer_Part_Number" "TP4056")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "1A Standalone Linear Li-lon Battery Charger, SOP-8")
    (property "Datasheet_Link" "https://dlnmh9ip6v2uc.cloudfront.net/datasheets/Prototyping/TP4056.pdf")
    (property "symbolName1" "TP4056")
)
