M48
; DRILL file {KiCad 9.0.0-rc2} date 2026-08-26T19:50:22+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-26T19:50:22+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-rc2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X104.505Y-52.71
X104.505Y-58.49
T2
X147.4Y-121.25
X152.7Y-121.25
M30
